-- таблица доходов
CREATE TABLE IF NOT EXISTS incomes (
  id INTEGER PRIMARY KEY,
  date DATETIME NOT NULL,
  amount REAL NOT NULL,
  owner TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT '',
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- таблица расходов
CREATE TABLE IF NOT EXISTS costs (
  id INTEGER PRIMARY KEY,
  date DATETIME NOT NULL,
  amount REAL NOT NULL,
  owner TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT '',
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);